language: node_js
node_js: '7.10.1'
sudo: false
dist: trusty

matrix:
  fast_finish: true
  include:
  - os: linux
    python: '2.7' # for PlatformIO
  - os: osx
    osx_image: xcode8.3

addons:
  apt:
    packages:
    - libudev-dev
    - rpm

git:
  depth: 5

env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - packages/xod-arduino-deploy/node_modules
  - packages/xod-arduino/node_modules
  - packages/xod-cli/node_modules
  - packages/xod-client-browser/node_modules
  - packages/xod-client-electron/node_modules
  - packages/xod-client/node_modules
  - packages/xod-fs/node_modules
  - packages/xod-func-tools/node_modules
  - packages/xod-project/node_modules
  - packages/xod-patch-search/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds
  - $HOME/.platformio
  yarn: true
  pip: true

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.3
- export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    pip install -U platformio;
  fi


before_script: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3; # give xvfb some time to start
  fi

script:
- yarn build
- yarn lint
- yarn test
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then yarn test-cpp; fi
- yarn test-func
- travis_wait 50 ./tools/travis.sh
